control_homepage:
    pattern:  /
    defaults: { _controller: ControlBundle:Default:index }

ControlBundle_cuenta:
    resource: "@ControlBundle/Resources/config/routing/cuenta.yml"
    prefix: /cuenta
    
ControlBundle_categoria:
    resource: "@ControlBundle/Resources/config/routing/categoria.yml"
    prefix: /categoria
    
ControlBundle_tipocuenta:
    resource: "@ControlBundle/Resources/config/routing/tipocuenta.yml"
    prefix: /tipocuenta
    
ControlBundle_usuario:
    resource: "@ControlBundle/Resources/config/routing/usuario.yml"
    prefix: /usuario
    
ControlBundle_cuota:
    resource: "@ControlBundle/Resources/config/routing/cuota.yml"
    prefix: /cuota

ControlBundle_formapago:
    resource: "@ControlBundle/Resources/config/routing/formapago.yml"
    prefix: /formapago