parameters:
#    control.example.class: ControlCuentas\ControlBundle\Example

services:
#    control.example:
#        class: %control.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
